// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        string
	Sender    string
	Receiver  string
	RoomID    pgtype.Text
	Body      pgtype.Text
	CreatedAt pgtype.Timestamp
}

type Room struct {
	ID        string
	RoomName  string
	CreatedAt pgtype.Timestamp
}

type RoomMembership struct {
	ID       string
	UserID   string
	RoomID   string
	JoinedAt pgtype.Timestamp
	LeftAt   pgtype.Timestamp
}

type User struct {
	ID        string
	FirstName string
	LastName  string
	Email     string
	Phone     pgtype.Text
	CreatedAt pgtype.Timestamp
}
